// <auto-generated />
using System;
using CustomerServicesSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerServicesSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.BookedStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookedStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5854),
                            IsActive = true,
                            Name = "Yes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5856),
                            IsActive = true,
                            Name = "No"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5858),
                            IsActive = true,
                            Name = "Pending"
                        });
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.CallCenterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookedStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("CallPurposeId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("FileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutcomeOfCallId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookedStatusId");

                    b.HasIndex("CallPurposeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NationalityId");

                    b.HasIndex("OutcomeOfCallId");

                    b.HasIndex("SourceId");

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("VisitTypeId");

                    b.ToTable("CallCenterRecords");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.CallPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CallPurposes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5256),
                            IsActive = true,
                            Name = "Book appointment"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5271),
                            IsActive = true,
                            Name = "Offer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5273),
                            IsActive = true,
                            Name = "Service Price"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5274),
                            IsActive = true,
                            Name = "Follow Up"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5276),
                            IsActive = true,
                            Name = "Complaint"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5277),
                            IsActive = true,
                            Name = "Inquiry"
                        });
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5901),
                            IsActive = true,
                            Name = "Kuwaiti"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5904),
                            IsActive = true,
                            Name = "Non-Kuwaiti"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5905),
                            IsActive = true,
                            Name = "Saudi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5906),
                            IsActive = true,
                            Name = "Egyptian"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5908),
                            IsActive = true,
                            Name = "Indian"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5909),
                            IsActive = true,
                            Name = "Filipino"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5911),
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.OutcomeOfCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutcomesOfCall");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5801),
                            IsActive = true,
                            Name = "Outdoor Marketing"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5803),
                            IsActive = true,
                            Name = "WhatsApp"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5804),
                            IsActive = true,
                            Name = "Phone Call"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5806),
                            IsActive = true,
                            Name = "Walk In"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5807),
                            IsActive = true,
                            Name = "Online"
                        });
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.VisitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VisitTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5741),
                            IsActive = true,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 22, 11, 53, 39, 392, DateTimeKind.Local).AddTicks(5745),
                            IsActive = true,
                            Name = "Revisit"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.CallCenterRecord", b =>
                {
                    b.HasOne("CustomerServicesSystem.Models.BookedStatus", "BookedStatus")
                        .WithMany("Records")
                        .HasForeignKey("BookedStatusId");

                    b.HasOne("CustomerServicesSystem.Models.CallPurpose", "CallPurpose")
                        .WithMany("Records")
                        .HasForeignKey("CallPurposeId");

                    b.HasOne("CustomerServicesSystem.Models.Department", "Department")
                        .WithMany("Records")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("CustomerServicesSystem.Models.Doctor", "Doctor")
                        .WithMany("Records")
                        .HasForeignKey("DoctorId");

                    b.HasOne("CustomerServicesSystem.Models.Nationality", "Nationality")
                        .WithMany("Records")
                        .HasForeignKey("NationalityId");

                    b.HasOne("CustomerServicesSystem.Models.OutcomeOfCall", "OutcomeOfCall")
                        .WithMany("Records")
                        .HasForeignKey("OutcomeOfCallId");

                    b.HasOne("CustomerServicesSystem.Models.Source", "Source")
                        .WithMany("Records")
                        .HasForeignKey("SourceId");

                    b.HasOne("CustomerServicesSystem.Models.StaffMember", "StaffMember")
                        .WithMany("Records")
                        .HasForeignKey("StaffMemberId");

                    b.HasOne("CustomerServicesSystem.Models.VisitType", "VisitType")
                        .WithMany("Records")
                        .HasForeignKey("VisitTypeId");

                    b.Navigation("BookedStatus");

                    b.Navigation("CallPurpose");

                    b.Navigation("Department");

                    b.Navigation("Doctor");

                    b.Navigation("Nationality");

                    b.Navigation("OutcomeOfCall");

                    b.Navigation("Source");

                    b.Navigation("StaffMember");

                    b.Navigation("VisitType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CustomerServicesSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CustomerServicesSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerServicesSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CustomerServicesSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.BookedStatus", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.CallPurpose", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.Department", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.Doctor", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.Nationality", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.OutcomeOfCall", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.Source", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.StaffMember", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CustomerServicesSystem.Models.VisitType", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
